import { Check, Copy, Loader2, Play, RefreshCw, Square } from "lucide-react";
import { memo, useCallback, useMemo, useState } from "react";
import { groupCitationsByPage } from "@/lib/citations";
import { copyToClipboard } from "@/lib/copy-to-clipboard";
import { TOAST_DURATION, type CSSVars } from "@/lib/ui";
import type { Mode, ModeState } from "@/lib/hooks/use-narration-stream";
import type { ModeMeta } from "@/components/analyst/narration-modes";
import { Narration } from "@/components/analyst/narration-render";
import { SourceChip } from "@/components/analyst/source-chip";

// One reading lens fills the pane; siblings keep streaming in the background.
export const ReadingPane = memo(function ReadingPane({
  meta,
  state,
  startMode,
  stopMode,
}: {
  meta: ModeMeta;
  state: ModeState;
  startMode: (mode: Mode, opts?: { forceRefresh?: boolean }) => void;
  stopMode: (mode: Mode) => void;
}) {
  const [copied, setCopied] = useState(false);
  const isStreaming = state.status === "streaming";
  const hasText = state.text.length > 0;
  const isDone = state.status === "done";
  const isError = state.status === "error";
  const isCancelled = state.status === "cancelled";

  // Re-run (hasText) forces a fresh LLM call; first run may serve from cache.
  const ActionIcon = isStreaming ? Square : hasText ? RefreshCw : Play;
  const actionLabel = isStreaming
    ? `Stop ${meta.title}`
    : hasText
      ? `Re-run (fresh) ${meta.title}`
      : `Run ${meta.title}`;
  const handleAction = isStreaming
    ? () => stopMode(meta.key)
    : hasText
      ? () => startMode(meta.key, { forceRefresh: true })
      : () => startMode(meta.key);

  const citationPages = useMemo(
    () => groupCitationsByPage(state.citations),
    [state.citations],
  );

  const onCopy = useCallback(async () => {
    if (!state.text) return;
    if (await copyToClipboard(state.text)) {
      setCopied(true);
      setTimeout(() => setCopied(false), TOAST_DURATION);
    }
  }, [state.text]);

  return (
    <section
      className="ewl-reading"
      style={{ "--lens": meta.accent } as CSSVars}
      aria-label={meta.title}
    >
      <header className="flex items-start gap-3 px-5 pt-3.5 pb-3 shrink-0">
        <div className="min-w-0 flex-1 space-y-1.5">
          <h3 className="flex items-baseline gap-2 min-w-0 text-[18px] font-semibold text-text leading-tight m-0">
            <span
              aria-hidden="true"
              className="h-2.5 w-[3px] rounded-[2px] shrink-0 translate-y-px"
              style={{ background: meta.accent }}
            />
            {meta.title}
          </h3>
          {(isStreaming || isDone) && (
            <div className="ewl-read-dateline">
              {/* model_id rides the badge tooltip — too technical for the
                  always-visible line. */}
              {isStreaming ? (
                <span className="fresh">Generating…</span>
              ) : state.cached ? (
                <span
                  className="cached inline-flex items-center gap-1.5"
                  title={`Saved from an earlier run — re-run for a fresh take.${
                    state.modelId ? `\nGenerated by ${state.modelId}` : ""
                  }`}
                >
                  <span
                    className="h-1.5 w-1.5 rounded-full bg-current shrink-0"
                    aria-hidden="true"
                  />
                  Cached
                </span>
              ) : (
                <span
                  className="fresh inline-flex items-center gap-1.5"
                  title={state.modelId ? `Generated by ${state.modelId}` : undefined}
                >
                  {/* Mono dot, not a sparkle — the "AI did this" cliché this
                      console avoids. */}
                  <span
                    className="h-1.5 w-1.5 rounded-full bg-current shrink-0"
                    aria-hidden="true"
                  />
                  Fresh
                </span>
              )}
            </div>
          )}
        </div>
        <div className="flex items-center gap-1.5 shrink-0">
          <button
            type="button"
            onClick={handleAction}
            aria-label={actionLabel}
            title={actionLabel}
            className="grid place-items-center w-8 h-8 rounded-md border border-border text-muted hover:text-text hover:bg-panel-elev focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:text-text focus-visible:bg-panel-elev transition-colors shrink-0"
          >
            <ActionIcon className="h-3.5 w-3.5 fill-current" aria-hidden="true" />
          </button>
          <button
            type="button"
            onClick={onCopy}
            disabled={!state.text}
            aria-label={`Copy ${meta.title}`}
            title={state.text ? `Copy ${meta.title}` : "Nothing to copy yet"}
            className="grid place-items-center w-8 h-8 rounded-md border border-border text-muted hover:text-text hover:bg-panel-elev focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:text-text focus-visible:bg-panel-elev disabled:opacity-40 disabled:cursor-not-allowed transition-colors shrink-0"
          >
            {copied ? (
              <Check className="h-3.5 w-3.5 text-up" aria-hidden="true" />
            ) : (
              <Copy className="h-3.5 w-3.5" aria-hidden="true" />
            )}
          </button>
        </div>
      </header>

      {/* Natural height — the scroll-stack column scrolls, not this box.
          aria-live announces streamed text + status swaps to SR. */}
      <div className="px-5 pb-4" aria-live="polite" aria-busy={isStreaming}>
        {state.text ? (
          <div className="ewl-read-body">
            <Narration text={state.text} streaming={isStreaming} accent={meta.accent} />
            {isCancelled && (
              <p className="mt-4 text-[11px] uppercase tracking-[0.12em] text-muted font-semibold">
                <span aria-hidden="true">⏹</span> Stopped at {state.tokens} tokens ·
                click <span aria-hidden="true">↻</span> to retry
              </p>
            )}
            {state.fellBack && !isStreaming && (
              <div className="mt-4 px-3 py-2 rounded-md text-[13px] leading-snug border border-warn/30 bg-warn/8 text-warn flex items-start gap-2">
                <span aria-hidden="true">⚠</span>
                <span>
                  Couldn’t verify this against the source text — showing a safe
                  summary instead. Re-run <span aria-hidden="true">↻</span> for a
                  fresh take.
                </span>
              </div>
            )}
          </div>
        ) : isStreaming ? (
          <div className="space-y-3 pt-1">
            <div className="flex items-center gap-2 text-[13px] text-muted">
              <Loader2 className="h-3.5 w-3.5 animate-spin text-accent" aria-hidden="true" />
              Waiting for tokens…
            </div>
            <div className="space-y-2">
              <div className="ewl-skeleton h-3.5 w-full" />
              <div className="ewl-skeleton h-3.5 w-[92%]" />
              <div className="ewl-skeleton h-3.5 w-[97%]" />
              <div className="ewl-skeleton h-3.5 w-[78%]" />
            </div>
          </div>
        ) : isError ? (
          <div className="space-y-2 pt-1">
            <div className="text-[12px] uppercase tracking-[0.12em] font-semibold text-down">
              Error
            </div>
            <p className="text-[13px] ewl-num text-down bg-down-soft border border-down/30 rounded-md p-3">
              {state.error}
            </p>
            <button
              type="button"
              onClick={() => startMode(meta.key)}
              className="inline-flex items-center gap-1.5 text-[13px] font-semibold text-accent-bright hover:underline rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent"
            >
              <RefreshCw className="h-3 w-3" aria-hidden="true" /> Retry
            </button>
          </div>
        ) : (
          // Idle / cancelled-before-tokens.
          <div className="ewl-read-body min-h-[clamp(180px,30vh,360px)] flex flex-col justify-center py-2">
            <p className="text-[15px] text-text-dim leading-relaxed m-0">
              {meta.subtitle}{" "}
              <span className="text-faint">Not generated yet.</span>
            </p>
            <button
              type="button"
              onClick={() => startMode(meta.key)}
              className="ewl-read-run mt-3 self-start focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-accent focus-visible:ring-offset-2 focus-visible:ring-offset-bg"
            >
              <Play className="h-3.5 w-3.5 fill-current" aria-hidden="true" />
              Run this read
            </button>
          </div>
        )}
      </div>

      {(citationPages.length > 0 || state.tokens > 0) && (
        <footer className="ewl-read-meta shrink-0 px-5 py-2.5 border-t border-border">
          {citationPages.length > 0 && !isStreaming && (
            <span className="flex flex-wrap items-center gap-1.5">
              <span className="uppercase tracking-[0.14em] text-muted">
                Sources
              </span>
              {citationPages.map(([page, sentences]) => (
                <SourceChip key={page} page={page} sentences={sentences} />
              ))}
            </span>
          )}
          {state.tokens > 0 && (
            // No tok/s while typing — that rate is typewriter pacing, not the model's.
            <span className="ml-auto flex items-center gap-1.5 shrink-0 ewl-num">
              <span>
                <strong>{state.tokens}</strong> tok
              </span>
              {!isStreaming && state.genMs != null && (
                <>
                  <span className="sep" aria-hidden="true">·</span>
                  <span title="Model generation time (excludes the typewriter reveal)">
                    <strong>{(state.genMs / 1000).toFixed(1)}</strong>s
                  </span>
                </>
              )}
            </span>
          )}
        </footer>
      )}
    </section>
  );
});
